export const audienceTargetingTimezones: Record<string, string> = {
  'emea executives': 'Europe/London',
  'apac developers': 'Asia/Singapore',
  'na c-suite': 'America/New_York',
  'latam finance leaders': 'America/Sao_Paulo',
  'japan security buyers': 'Asia/Tokyo',
  'australia it directors': 'Australia/Sydney',
  'india cloud architects': 'Asia/Kolkata',
  'germany manufacturing leaders': 'Europe/Berlin',
  'france data executives': 'Europe/Paris',
  'middle east cio network': 'Asia/Dubai',
  'uk procurement teams': 'Europe/London',
  'us healthcare executives': 'America/Chicago',
  'canada fintech founders': 'America/Toronto',
  'korea platform engineers': 'Asia/Seoul',
  'asean growth marketers': 'Asia/Jakarta',
}

export const liveCampaignSpendData = [
  { campaignName: 'Q3 Cloud Migration - NA', spendToday: 1250.5, utilization: '85%' },
  { campaignName: 'Zero Trust Security Lead Gen', spendToday: 3480.75, utilization: '92%' },
  { campaignName: 'GenAI Webinar - EMEA', spendToday: 430, utilization: '20%' },
  { campaignName: 'Hybrid Cloud CFO Briefing', spendToday: 2875.25, utilization: '74%' },
  { campaignName: 'Enterprise Data Fabric Awareness', spendToday: 1995.9, utilization: '63%' },
  { campaignName: 'APAC Developer Platform Trial', spendToday: 765.4, utilization: '38%' },
  { campaignName: 'CISO Ransomware Readiness', spendToday: 4210.1, utilization: '97%' },
  { campaignName: 'AI Governance Executive Forum', spendToday: 1590.35, utilization: '56%' },
  { campaignName: 'Manufacturing IoT Modernization', spendToday: 3125.8, utilization: '81%' },
  { campaignName: 'FinOps Cost Optimization - Global', spendToday: 2388.6, utilization: '69%' },
  { campaignName: 'CRM Integration ABM Pilot', spendToday: 1188.45, utilization: '44%' },
  { campaignName: 'Secure Access Service Edge Launch', spendToday: 4520.3, utilization: '95%' },
  { campaignName: 'Data Warehouse Migration - UKI', spendToday: 980.2, utilization: '31%' },
  { campaignName: 'Marketing Automation MQL Surge', spendToday: 2215.15, utilization: '58%' },
  { campaignName: 'Healthcare Compliance Cloud', spendToday: 3670.95, utilization: '88%' },
  { campaignName: 'Financial Services Risk Analytics', spendToday: 4985.5, utilization: '99%' },
  { campaignName: 'Retail Personalization Platform', spendToday: 1745.65, utilization: '52%' },
  { campaignName: 'Supply Chain Control Tower', spendToday: 2640.25, utilization: '73%' },
  { campaignName: 'DevSecOps Pipeline Acceleration', spendToday: 3390.4, utilization: '86%' },
  { campaignName: 'Kubernetes Management - EMEA', spendToday: 1410.8, utilization: '47%' },
  { campaignName: 'Observability Platform Demo', spendToday: 890.55, utilization: '29%' },
  { campaignName: 'Identity Governance Lead Gen', spendToday: 3860.7, utilization: '91%' },
  { campaignName: 'Cloud ERP Modernization', spendToday: 2465.35, utilization: '67%' },
  { campaignName: 'B2B Commerce Transformation', spendToday: 1720.95, utilization: '49%' },
  { campaignName: 'Mainframe Modernization CIO', spendToday: 4588.2, utilization: '96%' },
  { campaignName: 'Data Privacy Automation', spendToday: 2035.45, utilization: '61%' },
  { campaignName: 'Contact Center AI Assist', spendToday: 1345.1, utilization: '42%' },
  { campaignName: 'Partner Ecosystem Marketplace', spendToday: 710.75, utilization: '24%' },
  { campaignName: 'Edge Computing for Telco', spendToday: 3295.55, utilization: '79%' },
  { campaignName: 'SaaS Spend Management - NA', spendToday: 1895.3, utilization: '55%' },
  { campaignName: 'HR Analytics CHRO Roundtable', spendToday: 1045.9, utilization: '36%' },
  { campaignName: 'Legal Ops Contract AI', spendToday: 2755.85, utilization: '72%' },
  { campaignName: 'Customer Data Platform ABM', spendToday: 3915.2, utilization: '89%' },
  { campaignName: 'API Security Buyer Intent', spendToday: 3160.6, utilization: '83%' },
  { campaignName: 'Sustainability Reporting SaaS', spendToday: 1455.75, utilization: '46%' },
  { campaignName: 'Board Cyber Risk Briefing', spendToday: 4780.4, utilization: '98%' },
  { campaignName: 'Database Reliability Engineering', spendToday: 2290.1, utilization: '65%' },
  { campaignName: 'Enterprise Search AI Launch', spendToday: 1665.55, utilization: '51%' },
  { campaignName: 'Low-Code Automation COE', spendToday: 930.35, utilization: '28%' },
  { campaignName: 'Procurement Analytics Suite', spendToday: 2575.95, utilization: '70%' },
  { campaignName: 'Insurance Claims Automation', spendToday: 3445.8, utilization: '84%' },
  { campaignName: 'Public Sector Cloud Security', spendToday: 2975.25, utilization: '76%' },
  { campaignName: 'Private Equity Portfolio Tech', spendToday: 1815.45, utilization: '53%' },
  { campaignName: 'Revenue Intelligence Platform', spendToday: 2135.65, utilization: '62%' },
  { campaignName: 'Analytics Modernization - LATAM', spendToday: 1210.2, utilization: '39%' },
  { campaignName: 'Developer Experience Benchmark', spendToday: 555.75, utilization: '18%' },
  { campaignName: 'CFO Planning Transformation', spendToday: 4055.15, utilization: '90%' },
  { campaignName: 'ITSM Automation Expansion', spendToday: 1535.85, utilization: '48%' },
  { campaignName: 'Enterprise Backup Resilience', spendToday: 3655.3, utilization: '87%' },
  { campaignName: 'AI Security Operations Center', spendToday: 4888.9, utilization: '99%' },
]

